import os
from dotenv import load_dotenv

load_dotenv()


class Config:
    AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
    AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY", "")
    AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
    AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-01")
    AZURE_TRANSLATOR_ENDPOINT = os.getenv("AZURE_TRANSLATOR_ENDPOINT", "")
    AZURE_TRANSLATOR_KEY = os.getenv("AZURE_TRANSLATOR_KEY", "")
    AZURE_TRANSLATOR_REGION = os.getenv("AZURE_TRANSLATOR_REGION", "")
    AZURE_CONTENT_SAFETY_ENDPOINT = os.getenv("AZURE_CONTENT_SAFETY_ENDPOINT", "")
    AZURE_CONTENT_SAFETY_KEY = os.getenv("AZURE_CONTENT_SAFETY_KEY", "")
    COSMOSDB_ACCOUNT_URI = os.getenv("COSMOSDB_ACCOUNT_URI", "")
    COSMOSDB_ACCOUNT_KEY = os.getenv("COSMOSDB_ACCOUNT_KEY", "")
    COSMOSDB_DATABASE_NAME = os.getenv("COSMOSDB_DATABASE_NAME", "mediguide")
    COSMOSDB_CONTAINER_NAME = os.getenv("COSMOSDB_CONTAINER_NAME", "sessions")
    MAX_FILE_SIZE_MB = 10
    ALLOWED_PDF_EXTENSIONS = {".pdf"}
    ALLOWED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
